// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _u32_to_u32_table{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const u32 * k1, const u32 * k2);
  const size_t sizes[2];

  u32 * key;
  u32 * value;
  icy_mem * key_area;
  icy_mem * value_area;
}u32_to_u32_table;

u32_to_u32_table * u32_to_u32_table_create(const char * optional_name);
void u32_to_u32_table_set(u32_to_u32_table * table, u32 key, u32 value);
void u32_to_u32_table_insert(u32_to_u32_table * table, u32 * key, u32 * value, size_t count);
void u32_to_u32_table_lookup(u32_to_u32_table * table, u32 * keys, size_t * out_indexes, size_t count);
void u32_to_u32_table_remove(u32_to_u32_table * table, u32 * keys, size_t key_count);
void u32_to_u32_table_clear(u32_to_u32_table * table);
void u32_to_u32_table_unset(u32_to_u32_table * table, u32 key);
bool u32_to_u32_table_try_get(u32_to_u32_table * table, u32 * key, u32 * value);
void u32_to_u32_table_print(u32_to_u32_table * table);
size_t u32_to_u32_table_iter(u32_to_u32_table * table, u32 * keys, size_t keycnt, u32 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
